development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV["REDIS_URL"] || "redis://localhost:6379" %>
 
production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] || "redis://localhost:6379"%>
